### ISSUE TITLE
Sounds from UT pliz

### ISSUE THREAD

**Issue by runarmyklebust** [GlennRicaud/foos-app#10]
http://unrealtournament.99.free.fr/utfiles/index.php?dir=sound%20ut/
- First Blood
- Dominating > e.g 3 in a row
- Ownage > 6
- Whicked sick > 9
- Godlike = 10 

👍 👍 👍 👍 👍 👍

**Comment by aro** [comment]
Done, a bit easier:
- First Blood
- Dominating -> 3 in a row
- Ownage -> 5 in a row
- Whicked sick -> 7 in a row
- Godlike -> 8 in a row
