### ISSUE TITLE
Login page for players

### ISSUE THREAD

**Issue by aro** [GlennRicaud/foos-app#26]
Maybe use IdProvider to log in using gmail, etc.
First step to be able to post comments in games, and update the user profile.

**Comment by GlennRicaud** [comment]
For that, we will need foos to run on Enonic XP 6.8.
I have updated the dockerfile to use 6.8.0-RC2. 
@z127545 Can you restart the server

**Comment by diegopasten** [comment]
Can this be closed @GlennRicaud / @aro
