### ISSUE TITLE
Make foos gender aware

### ISSUE THREAD

**Issue by jsi** [GlennRicaud/foos-app#28]
to avoid problems like this:

![screenshot 2016-11-07 12 18 20](https://cloud.githubusercontent.com/assets/477453/20056256/896f99b4-a4e5-11e6-9069-20179268f5c1.png)

**Comment by aro** [comment]
@jsi I made it gender neutral instead, just changed the text. It was a simple change. Adding gender to players was more work, and I'm not sure it will be more useful for now.
Can we close this?
